name: Alma Configuration Changes Template
description: Description of a proposed changes to the configuration in Alma
title: Alma Configuration Changes Template
labels: ['config-changes']
body:
  - type: markdown
    attributes:
      value: "### Alma Configuration Changes"
  - type: markdown
    attributes:
      value: "#### *(fields with an asterisk are required)*"
  - type: input
    id: requestor
    attributes:
      label: Name and role of change requestor 
    validations:
      required: true
  - type: input
    id: change_type
    attributes:
      label: What kind of change
    validations:
      required: true       
  - type: textarea
    id: change_summary
    attributes:
      label: Justification for Change
    validations:
      required: true    
  - type: textarea
    id: change_impact
    attributes:
      label: Anticpated impact of change
    validations:
      required: true 
  - type: textarea
    id: test_plan
    attributes:
      label: Pre-implementation test plan
    validations:
      required: true    
  - type: textarea
    id: back_out_plan
    attributes:
      label: Back out plan
    validations:
      required: true    
  - type: input
    id: approvals
    attributes:
      label: Approvals (may vary by the type of change)
    validations:
      required: true     
  - type: textarea
    id: post_test_plan
    attributes:
      label: Post-implementation testing requirements
    validations:
      required: true       
      
