name: Alma Configuration Changes Template
description: Description of a proposed changes to the configuration in Alma
title: Alma Configuration Changes Template
labels: ['config-changes']
body:
  - type: markdown
    attributes:
      value: "### Alma Configuration Changes"
  - type: markdown
    attributes:
      value: "#### *(fields with an asterisk are required)*"
  - type: input
    id: requestor
    attributes:
      label: Name and role of change requestor *
    validations:
      required: true 
  - type: input
    id: project_lead
    attributes:
      label: Project lead *
    validations:
      required: true
  - type: input
    id: project_reviewer
    attributes:
      label: Reviewer *
    validations:
      required: true
  - type: input
    id: record_count
    attributes:
      label: Number of records involved, if known
  - type: markdown
    attributes:
      value: "### Process components (check all that apply):"
  - type: checkboxes
    id: download_method
    attributes:
      label: "Export records using"
      options:
        - label: Alma export job
        - label: Z39.50/SRU (includes MarcEdit client)
        - label: OCLC Connexion Client
        - label: External script (Python, Ruby, XQuery/XSLT, REST APIs)
        - label: Other (provide details below)
        - label: N/A
  - type: checkboxes
    id: transform_method
    attributes:
      label: "Transform records using"
      options:
        - label: Alma normalization rule/process
        - label: Alma job
        - label: OCLC Connexion Client macro
        - label: MarcEdit task list
        - label: External script
        - label: Other (provide details below)
        - label: N/A
  - type: checkboxes
    id: import_method
    attributes:
      label: "Import records using"
      options:
        - label: Alma import profile
        - label: Alma-WorldCat integration
        - label: Alma-MarcEdit integration
        - label: OCLC Connexion Client
        - label: External script
        - label: Other (provide details below)
        - label: N/A

