name: Alma Configuration Changes Template
description: Description of a proposed changes to the configuration in Alma
title: Alma Configuration Changes Template
labels: ['config-changes']
body:
  - type: markdown
    attributes:
      value: "### Alma Configuration Changes"
  - type: markdown
    attributes:
      value: "#### *(fields with an asterisk are required)*"
  - type: input
    id: requestor
    attributes:
      label: Name and role of change requestor *
    validations:
      required: true 
  - type: input
    id: change_type
    attributes:
      label: ype of change (ex: Major, Minor, Emergency) with brief description of each issue *
    validations:
      required: true       
